name: Test compare
on:
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled]

jobs:
  run:
    if: contains(github.event.pull_request.labels.*.name, 'test-compare')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Test compare
        uses: nearform-actions/github-action-test-compare@master
        with:
          tests: 'test.js'
          testCommand: 'node test.js'
          installCommand: 'echo "" > /dev/null'
